TravelTripProje/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProje.Models.Siniflar;

namespace TravelTripProje.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        //Context sınıfından c nesnesi türetildi
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Hakkimizdas.ToList();
            return View(degerler);
        }
    }
}

TravelTripProje/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProje.Models.Siniflar;

namespace TravelTripProje.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Blogs.OrderBy(x=>Guid.NewGuid()).Take(8).ToList();    
          
            return View(degerler);
        }
        public ActionResult About()
        {
            return View();
        }
        public PartialViewResult Partial1()
        {
            var degerler = c.Blogs.OrderByDescending(x => x.ID).Take(2).ToList();
            return PartialView(degerler);
        }
        public PartialViewResult Partial2() 
        {
            var deger = c.Blogs.Where(x => x.ID == 1).ToList();
            return PartialView(deger);
        }
        public PartialViewResult Partial3() 
        {
            var deger = c.Blogs.Take(10).ToList();
            return PartialView(deger);
        }
        public PartialViewResult Partial4()
        {
            var deger = c.Blogs.Take(3).ToList();
            return PartialView(deger);  
        }
        public PartialViewResult Partial5()
        {
            var deger = c.Blogs.Take(3).OrderByDescending(x => x.ID).ToList();
            return PartialView(deger);
        }
    }
}

TravelTripProje/Views/Default/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<div class="content">
    <div class="wrap">
        <div class="about">
            <h3>Hakkımızda</h3>
            <img src="~/web/images/about_banner.jpg" alt="" />
            <p>Lorem ipsum dolor sit amet,  </p>
           
        </div>
    </div>
</div>

TravelTripProje/Views/Default/Index.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>

<body>
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot" style="margin-left:80px;">Tatil & Seyahat Bloğum</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restaurantlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Uçuşlar</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Yapılacak Şeyler</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Araç Kiralama</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider" style="width:650px; height:450px;" >
                            <ul class="rslides" id="slider1">
                                @foreach (var x in Model)
                                {
                                    <li><img src="@x.BlogImage" alt=""></li>
                                    @*<li><img src="~/web/images/img2.jpg" alt=""></li>
                                        <li><img src="~/web/images/img3.jpg" alt=""></li>
                                        <li><img src="~/web/images/img4.jpg" alt=""></li>*@
                                }

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Tatil Seyahat Bloğuma Hoşgeldiniz!</h3>
                    <p>Gezip gördüğüm yerleri sizlerle paylaşmak için kodlamasını tamamen kendim yaptığım MVC5 üzerine kurulu dinamik bir web projesi geliştirdim.Hem TÜRKİYE'den hem de yurt dışından gezip gördüğüm yerleri blog yazıları olarak sizlerle paylaşma niyetindeyim.Umuyorum ki yazdıklarımı beğenirsiniz, keyifli okumalar, sağlıklı günler...  </p>
                </div>
                @Html.Action("Partial1", "Default")
                <div class="grids">
                    <div class="box1">

                        @Html.Action("Partial3", "Default")
                        @Html.Action("Partial4", "Default")
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

TravelTripProje/Views/Default/Partial1.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>

<div class="con-bot">
    @foreach (var x in Model)
    {
    <div class="left">
        <div class="bot-left">
            <img src="@x.BlogImage" alt="" style="aspect-ratio:4/3" />
        </div>
        <div class="left-text">
            <h4>@x.Baslik</h4>
            <span class="doller">@x.Tarih.ToString("dd.MM.yyyy")</span>
            <p> @x.Aciklama.Substring(0, x.Aciklama.Substring(0, 80).LastIndexOf(" "))...</p>
            <p> <a href ="/Blog/BlogDetay/@x.ID"> <span class="read">Devamını Oku</span> </a> </p>
        </div>
    </div>
    }
    @Html.Action("Partial2", "Default")
   
    <div class="clear"></div>
</div>

TravelTripProje/Views/Default/Partial2.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog> 

@foreach (var x in Model)
{

<div class="right">
    <div class="bot-left">
        <img src="@x.BlogImage" alt="" style="aspect-ratio:4/3" />
    </div>
    <div class="left-text">
        <h4>@x.Baslik</h4>
        <span class="doller">@x.Tarih.ToString("dd.MM.yyyy")</span>
        <p> @x.Aciklama.Substring(0, x.Aciklama.Substring(0, 80).LastIndexOf(" "))... </p>
        <p> <a href ="/Blog/BlogDetay/@x.ID"><span class="read">Devamını Oku</span></a></p>
    </div>
</div>
}

TravelTripProje/Views/Default/Partial3.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>

<div class="padding">
    <h4>En Popüler 10 Blog</h4>
   
    <ul class="list list-pad">
        @{int i = 0; }
        @foreach (var x in Model)
        {
            <li class="list-bg"><span>@{i++;} @i.</span><a href="/Blog/BlogDetay/@x.ID">@x.Baslik</a></li>
        }
        </ul>
    
    <a href="/Blog/Index" class="link1">Tüm Blogları Gör</a>
</div>

TravelTripProje/Views/Default/Partial4.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>
<div class="padding1">
    <h4>En Beğendiğim Yerler</h4>
    <div class="box-left">
        @foreach (var x in Model)
        {
            <div class="bot-img">
                <img src="@x.BlogImage" style=" width:120px; height:80px;"  alt="" />
            </div>
            <div class="bot-desc">
                <p>@x.Aciklama.Substring(0, x.Aciklama.Substring(0, 100).LastIndexOf(" "))... </p>
            </div>
            <div class="clear"></div>
        }
    </div>
    @Html.Action("Partial5", "Default")
</div>

TravelTripProje/Views/Default/Partial5.cshtml
@using TravelTripProje.Models.Siniflar
@model List<Blog>
<div class="box1-left">
    @foreach (var x in Model)
    {
        <div class="bot-img">
            <img src="@x.BlogImage" style="width:120px; height:80px;" alt="" />
        </div>
        <div class="bot-desc1">
            <p> @x.Aciklama.Substring(0, x.Aciklama.Substring(0, 100).LastIndexOf(" "))... </p>
        </div>
        <div class="clear"></div>
    }
</div>